services:
  graphab-preprocessor:
    build: .
    image: graphab:latest # image name
    container_name: graphab
    volumes:
      - ./:/src
    environment:
      MINIO_API_URL: "${MINIO_API_URL}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"